#!/usr/bin/env php
<?php
require(__DIR__ . '/bootstrap.php');
$config = require(__DIR__ . '/config/console.php');
$app = new yii\console\Application($config);
$exitCode = $app->run();
exit($exitCode);
